- name: Test playbook
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Show Version
      ios_command:
        commands: show version
        provider:
          host: "{{ ansible_host }}"
          timeout: 300
          port: 22
          username: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"
      when: inventory_hostname in groups['cisco_ios']
    - name: Show Version
      junos_command:
        commands: show version
        provider:
          host: "{{ ansible_host }}"
          timeout: 300
          port: 22
          username: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"
      when: inventory_hostname in groups['junos']
