- name: Test playbook
  hosts: all
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ ansible_host }}"
      timeout: 300
      transport: cli
      port: 22
      username: root
      authorize: yes
      auth_pass: "test#1#1"
      password: "test#1#1"
  tasks:
    - name: Show Version
      ios_command:
        commands: show version
      when: inventory_hostname in groups['cisco-ios']
    - name: Show Version
      junos_command:
        commans: show version
      when: inventory_hostname in groups['junos']
