- name: Test playbook
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Show version
      napalm_cli:
        provider: "{{ dev_provider }}"
        args:
            commands:
                - show version
